---
- name: Create /opt/devops directory and file on CentOS and AWS Linux nodes
  hosts: all
  become: true
  tasks:
    - name: Ensure /opt/devops directory exists
      file:
        path: /opt/devops
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create info.txt file inside /opt/devops with content
      copy:
        dest: /opt/devops/info.txt
        content: "Hello from Ansible!"
        owner: root
        group: root
        mode: '0644'
